---
title: "include"
author: "Charlie"
date: "1/24/2020"
output: html_document
---
<h1 style="color:orange">Welcome on my Shiny App Page</h1>


## About ME 
I was born and raised in Hungary. I graduated here form high school.
After travelling around the world, I arrived to the USA. I liked it here and decided to learn the language and enrolled to college.
Outside of the office I like to spend my time with reading, cooking, running and backpacking to remote places. 


For my professinal experience, please visit my linkedIn [page](https://www.linkedin.com/in/karoly-lajko-18906b6/)


## About the Project
Any time I travel I enjoy observing cultures, traditions and  social habbits. Also, pay attention to what nations eat, drink and how healthy they are. 
**Cancer** is one of the main causes of death across the globe. 
There are many researches, experiments ongoing in this field that takes years to see
what is causing cancer to develop in the human body. 
The project shows various cancer rates of countries. 
It also visualizes on maps global food consumption vs cancer rates of the countries.
The question is: `Is there a relationship between what people eat and cancer development?`


[<span style="color:blue"> General information on Cancer </span>](https://www.who.int/cancer/PRGlobocanFinal.pdf)


## My Data Source

I choose my dataset from the OMCD  website:
[DATASET](https://stats.oecd.org//)

## The Shiny App content 
The following tabs are generated:
- Bar Chart
- Graph
- Table
- Readme

## Future Plans


Note that this page is  `UNDER DEVELOPMENT` and plan to update it continuously as my data science and coding skills improve. 
